const DATA_PATH = 'data.json';
const months = {"ม.ค.":1,"ก.พ.":2,"มี.ค.":3,"เม.ย.":4,"พ.ค.":5,"มิ.ย.":6,"ก.ค.":7,"ส.ค.":8,"ก.ย.":9,"ต.ค.":10,"พ.ย.":11,"ธ.ค.":12};
const monthNames = ["","ม.ค.","ก.พ.","มี.ค.","เม.ย.","พ.ค.","มิ.ย.","ก.ค.","ส.ค.","ก.ย.","ต.ค.","พ.ย.","ธ.ค."];
let allRows = [], chart = null, currentRange = 'all', currentSha = null;
function qs(id){return document.getElementById(id)}
function normalizeLabel(s){s=String(s||'').trim().replace(/\s+/g,' ');const m=s.match(/^(\d{1,2})\s*(ม\.ค\.|ก\.พ\.|มี\.ค\.|เม\.ย\.|พ\.ค\.|มิ\.ย\.|ก\.ค\.|ส\.ค\.|ก\.ย\.|ต\.ค\.|พ\.ย\.|ธ\.ค\.)$/);return m?`${Number(m[1])} ${m[2]}`:s}
function sortKey(label){const m=normalizeLabel(label).match(/^(\d{1,2})\s*(.+)$/);if(!m)return 99999;return (months[m[2]]||99)*100+Number(m[1])}
function nextDateLabel(label){const m=normalizeLabel(label).match(/^(\d{1,2})\s*(.+)$/);if(!m)return'';let d=Number(m[1]),mo=months[m[2]]||5;const dim={1:31,2:28,3:31,4:30,5:31,6:30,7:31,8:31,9:30,10:31,11:30,12:31};d++;if(d>dim[mo]){d=1;mo++}return `${d} ${monthNames[mo]||'พ.ค.'}`}
function movingAverage(rows,win,minP){return rows.map((_,i)=>{const slice=rows.slice(Math.max(0,i-win+1),i+1).map(r=>r.weight);if(slice.length<minP)return null;return +(slice.reduce((a,b)=>a+b,0)/slice.length).toFixed(2)})}
function buildRows(rows){const map=new Map();rows.forEach(r=>map.set(normalizeLabel(r.label),{label:normalizeLabel(r.label),weight:Number(r.weight)}));const arr=Array.from(map.values()).filter(r=>r.label&&Number.isFinite(r.weight)).sort((a,b)=>sortKey(a.label)-sortKey(b.label));const ma7=movingAverage(arr,7,3),ma14=movingAverage(arr,14,7);return arr.map((r,i)=>({...r,i,ma7:ma7[i],ma14:ma14[i]}))}
function getCfg(){return {owner:localStorage.gh_owner||'',repo:localStorage.gh_repo||'',branch:localStorage.gh_branch||'main',token:localStorage.gh_token||''}}
function setCfg(c){localStorage.gh_owner=c.owner;localStorage.gh_repo=c.repo;localStorage.gh_branch=c.branch;localStorage.gh_token=c.token}
function fillSettings(){const c=getCfg();qs('ownerInput').value=c.owner;qs('repoInput').value=c.repo;qs('branchInput').value=c.branch;qs('tokenInput').value=c.token}
function saveSettings(){setCfg({owner:qs('ownerInput').value.trim(),repo:qs('repoInput').value.trim(),branch:qs('branchInput').value.trim()||'main',token:qs('tokenInput').value.trim()});qs('settingsMsg').textContent='บันทึกค่าแล้ว';loadFromGithub()}
function apiUrl(){const c=getCfg();return `https://api.github.com/repos/${c.owner}/${c.repo}/contents/${DATA_PATH}?ref=${encodeURIComponent(c.branch)}`}
function validateCfg(){const c=getCfg();if(!c.owner||!c.repo||!c.branch||!c.token){qs('message').textContent='กรุณากรอก Owner/Repo/Branch/Token ก่อน';return false}return true}
function decodeB64Unicode(b64){const bin=atob(b64.replace(/\n/g,''));const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
function encodeB64Unicode(str){const bytes=new TextEncoder().encode(str);let bin='';bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin)}
async function loadFromGithub(){if(!validateCfg())return;qs('message').textContent='กำลังโหลดจาก GitHub...';const c=getCfg();const res=await fetch(apiUrl(),{headers:{Authorization:`Bearer ${c.token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}});if(!res.ok){qs('message').textContent=`โหลดไม่สำเร็จ: ${res.status} ${await res.text()}`;return}const file=await res.json();currentSha=file.sha;const parsed=JSON.parse(decodeB64Unicode(file.content));allRows=buildRows(parsed);updateUI('โหลดจาก GitHub แล้ว')}
async function saveToGithub(message){if(!validateCfg())return;const c=getCfg();const content=JSON.stringify(allRows.map(({label,weight})=>({label,weight})),null,2);const body={message,content:encodeB64Unicode(content),sha:currentSha,branch:c.branch};const res=await fetch(`https://api.github.com/repos/${c.owner}/${c.repo}/contents/${DATA_PATH}`,{method:'PUT',headers:{Authorization:`Bearer ${c.token}`,Accept:'application/vnd.github+json','Content-Type':'application/json','X-GitHub-Api-Version':'2022-11-28'},body:JSON.stringify(body)});if(!res.ok){qs('message').textContent=`บันทึกไม่สำเร็จ: ${res.status} ${await res.text()}`;return false}const out=await res.json();currentSha=out.content.sha;return true}
async function addOrUpdate(){const label=normalizeLabel(qs('dateInput').value);const weight=Number(String(qs('weightInput').value).replace(',','.'));if(!label||!Number.isFinite(weight)){qs('message').textContent='กรอกวันที่/น้ำหนักให้ถูกต้อง';return}allRows=buildRows([...allRows,{label,weight}]);updateUI(`กำลังบันทึก ${label} = ${weight.toFixed(2)}...`);const ok=await saveToGithub(`update weight ${label} = ${weight.toFixed(2)}`);if(ok){qs('weightInput').value='';qs('dateInput').value=nextDateLabel(label);updateUI('บันทึกเข้า GitHub แล้ว')}}
async function deleteLatest(){if(!allRows.length)return;const last=allRows[allRows.length-1];allRows=buildRows(allRows.slice(0,-1));updateUI(`กำลังลบ ${last.label}...`);const ok=await saveToGithub(`delete latest weight ${last.label}`);if(ok)updateUI('ลบล่าสุดจาก GitHub แล้ว')}
function setRange(r){currentRange=r;document.querySelectorAll('.chip').forEach(b=>b.classList.toggle('active',b.dataset.range===r));renderChart()}
function chartRows(){return currentRange==='all'?allRows:allRows.slice(-Number(currentRange))}
function updateUI(msg=''){if(!allRows.length)return;const latest=allRows[allRows.length-1],prev=allRows[allRows.length-2]||latest,low=allRows.reduce((a,b)=>b.weight<a.weight?b:a,allRows[0]);qs('subtitle').textContent=`อัปเดตถึง ${latest.label} = ${latest.weight.toFixed(2)} กก.`;qs('lowest').textContent=`${low.weight.toFixed(2)} กก.`;qs('lowestDate').textContent=low.label;qs('previous').textContent=`${prev.weight.toFixed(2)} กก.`;qs('previousDate').textContent=prev.label;qs('latest').textContent=`${latest.weight.toFixed(2)} กก.`;qs('latestDate').textContent=latest.label;qs('nextText').textContent=`ส่งต่อได้เลยครับพรุ่งนี้เช้า:\n${nextDateLabel(latest.label)} =`;qs('dateInput').value=nextDateLabel(latest.label);if(msg)qs('message').textContent=msg;renderChart()}
function copyNextText(){navigator.clipboard.writeText(qs('nextText').textContent);qs('message').textContent='คัดลอกแล้ว'}
function renderChart(){if(!allRows.length)return;const rows=chartRows();const labels=rows.map(r=>r.label);const datasets=[];if(qs('showDaily').checked)datasets.push({label:'น้ำหนักรายวัน',data:rows.map(r=>r.weight),borderColor:'#2563eb',backgroundColor:'#2563eb',tension:.25,pointRadius:3,borderWidth:2.5});if(qs('showMA7').checked)datasets.push({label:'เฉลี่ย 7 วัน',data:rows.map(r=>r.ma7),borderColor:'#f97316',backgroundColor:'#f97316',tension:.25,pointRadius:0,borderWidth:3});if(qs('showMA14').checked)datasets.push({label:'เฉลี่ย 14 วัน',data:rows.map(r=>r.ma14),borderColor:'#16a34a',backgroundColor:'#16a34a',tension:.25,pointRadius:0,borderWidth:3});if(chart)chart.destroy();chart=new Chart(qs('chart'),{type:'line',data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'top'},tooltip:{callbacks:{label:c=>`${c.dataset.label}: ${Number(c.raw).toFixed(2)} กก.`}}},scales:{y:{title:{display:true,text:'น้ำหนัก (กก.)'}},x:{ticks:{maxRotation:35,minRotation:35}}}}})}
fillSettings();
if(getCfg().owner) loadFromGithub(); else { allRows=buildRows([]); qs('message').textContent='กรอกค่า GitHub settings ก่อนใช้งาน'; }
